/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    teams: Team;
    sponsoren: Sponsoren;
    media: Media;
    dokumente: Dokumente;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    sponsoren: SponsorenSelect<false> | SponsorenSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    dokumente: DokumenteSelect<false> | DokumenteSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    eishockey: Eishockey;
    verein: Verein;
    einstellungen: Einstellungen;
  };
  globalsSelect: {
    eishockey: EishockeySelect<false> | EishockeySelect<true>;
    verein: VereinSelect<false> | VereinSelect<true>;
    einstellungen: EinstellungenSelect<false> | EinstellungenSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * News und Berichte für die Startseite.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  titel: string;
  /**
   * Das grosse Bild oben im Beitrag und auf der Startseite.
   */
  titelbild?: (number | null) | Media;
  /**
   * Ein bis zwei Sätze für die Vorschau auf der Startseite. Leer lassen ist auch in Ordnung.
   */
  auszug?: string | null;
  inhalt: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Weitere Fotos, die unter dem Text als Galerie erscheinen.
   */
  galerie?:
    | {
        bild: number | Media;
        id?: string | null;
      }[]
    | null;
  datum: string;
  /**
   * Optional. Der Beitrag erscheint dann auch auf der Teamseite.
   */
  team?: (number | null) | Team;
  /**
   * Wird automatisch gesetzt.
   */
  autor?: (number | null) | User;
  /**
   * Entsteht automatisch aus dem Titel.
   */
  slug?: string | null;
  typ?: ('news' | 'resultate') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Alle Fotos der Website. Einfach hierher ziehen zum Hochladen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Kurz beschreiben, was auf dem Bild zu sehen ist – hilft blinden Besucher:innen und Google.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    portrait?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Alle Mannschaften des EHC Rot-Blau.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: number;
  name: string;
  kategorie: 'aktiv' | 'nachwuchs' | 'breitensport';
  liga?: string | null;
  /**
   * Kleine Zahl = weiter vorne in der Liste.
   */
  reihenfolge?: number | null;
  /**
   * Erscheint in der Teamübersicht.
   */
  kurzbeschreibung?: string | null;
  teamfoto?: (number | null) | Media;
  beschreibung?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  trainer?:
    | {
        name: string;
        funktion?: string | null;
        email?: string | null;
        foto?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Kader mit Foto, Nummer und Position.
   */
  spieler?:
    | {
        name: string;
        nummer?: number | null;
        position?: ('goalie' | 'verteidigung' | 'sturm') | null;
        foto?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  trainingszeiten?:
    | {
        tag: 'Montag' | 'Dienstag' | 'Mittwoch' | 'Donnerstag' | 'Freitag' | 'Samstag' | 'Sonntag';
        zeit: string;
        ort?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Genau so schreiben, wie das Team auf sihf.ch erscheint, z. B. "EHC Rot-Blau Bern-Bümpliz".
   */
  sihfTeamName?: string | null;
  /**
   * Nummer aus der SIHF-Datenbank. Optional.
   */
  sihfTeamId?: string | null;
  /**
   * Nummer der Liga in der SIHF-Datenbank. Optional.
   */
  sihfLeagueId?: string | null;
  /**
   * Vollständige Adresse der Ranglisten-Seite auf sihf.ch.
   */
  tabellenUrl?: string | null;
  /**
   * Entsteht automatisch aus dem Namen.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Wer darf sich einloggen und Beiträge schreiben.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Autor:innen können nur Beiträge und Bilder anlegen.
   */
  role: 'autor' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Partner des Vereins – erscheinen auf der Startseite und der Sponsorenseite.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsoren".
 */
export interface Sponsoren {
  id: number;
  name: string;
  /**
   * Am besten mit weissem oder transparentem Hintergrund.
   */
  logo?: (number | null) | Media;
  website?: string | null;
  kategorie: 'hauptsponsor' | 'sponsor' | 'goenner';
  /**
   * Kleine Zahl = weiter vorne.
   */
  reihenfolge?: number | null;
  aktiv?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * PDFs wie Anmeldeformulare, Statuten oder Sponsoring-Unterlagen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dokumente".
 */
export interface Dokumente {
  id: number;
  /**
   * So wird der Download auf der Website benannt.
   */
  titel: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'teams';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'sponsoren';
        value: number | Sponsoren;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'dokumente';
        value: number | Dokumente;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  titel?: T;
  titelbild?: T;
  auszug?: T;
  inhalt?: T;
  galerie?:
    | T
    | {
        bild?: T;
        id?: T;
      };
  datum?: T;
  team?: T;
  autor?: T;
  slug?: T;
  typ?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  name?: T;
  kategorie?: T;
  liga?: T;
  reihenfolge?: T;
  kurzbeschreibung?: T;
  teamfoto?: T;
  beschreibung?: T;
  trainer?:
    | T
    | {
        name?: T;
        funktion?: T;
        email?: T;
        foto?: T;
        id?: T;
      };
  spieler?:
    | T
    | {
        name?: T;
        nummer?: T;
        position?: T;
        foto?: T;
        id?: T;
      };
  trainingszeiten?:
    | T
    | {
        tag?: T;
        zeit?: T;
        ort?: T;
        id?: T;
      };
  sihfTeamName?: T;
  sihfTeamId?: T;
  sihfLeagueId?: T;
  tabellenUrl?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsoren_select".
 */
export interface SponsorenSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  website?: T;
  kategorie?: T;
  reihenfolge?: T;
  aktiv?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        portrait?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dokumente_select".
 */
export interface DokumenteSelect<T extends boolean = true> {
  titel?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Regeln, Sommertraining, Shootingtraining und Goalie-Training.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eishockey".
 */
export interface Eishockey {
  id: number;
  /**
   * Kurzer Text oben auf der Seite.
   */
  einleitung?: string | null;
  /**
   * Die wichtigsten IIHF-Regeln einfach erklärt.
   */
  regeln?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  regelwerkLink?: string | null;
  /**
   * Sommertraining, Shootingtraining, Goalie-Training usw.
   */
  angebote?:
    | {
        titel: string;
        beschreibung?: string | null;
        termine?: string | null;
        ort?: string | null;
        kontakt?: string | null;
        bild?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Geschichte, Aktuelles und Vorstand.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verein".
 */
export interface Verein {
  id: number;
  gruendungsjahr?: number | null;
  geschichte?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  historischeBilder?:
    | {
        bild: number | Media;
        legende?: string | null;
        id?: string | null;
      }[]
    | null;
  aktuell?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  vorstand?:
    | {
        name: string;
        funktion: string;
        email?: string | null;
        telefon?: string | null;
        foto?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  mitgliedschaft?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  anmeldeformular?: (number | null) | Dokumente;
  statuten?: (number | null) | Dokumente;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Logo, Kontaktangaben und Sponsoring-Unterlagen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "einstellungen".
 */
export interface Einstellungen {
  id: number;
  vereinsname: string;
  logo?: (number | null) | Media;
  claim?: string | null;
  adresse?: string | null;
  email?: string | null;
  telefon?: string | null;
  eishalle?: string | null;
  sozialeMedien?:
    | {
        plattform: 'instagram' | 'facebook' | 'youtube' | 'tiktok';
        url: string;
        id?: string | null;
      }[]
    | null;
  sponsoringText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Wird auf der Sponsorenseite zum Download angeboten.
   */
  sponsoringBlatt?: (number | null) | Dokumente;
  sponsoringKontakt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eishockey_select".
 */
export interface EishockeySelect<T extends boolean = true> {
  einleitung?: T;
  regeln?: T;
  regelwerkLink?: T;
  angebote?:
    | T
    | {
        titel?: T;
        beschreibung?: T;
        termine?: T;
        ort?: T;
        kontakt?: T;
        bild?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verein_select".
 */
export interface VereinSelect<T extends boolean = true> {
  gruendungsjahr?: T;
  geschichte?: T;
  historischeBilder?:
    | T
    | {
        bild?: T;
        legende?: T;
        id?: T;
      };
  aktuell?: T;
  vorstand?:
    | T
    | {
        name?: T;
        funktion?: T;
        email?: T;
        telefon?: T;
        foto?: T;
        id?: T;
      };
  mitgliedschaft?: T;
  anmeldeformular?: T;
  statuten?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "einstellungen_select".
 */
export interface EinstellungenSelect<T extends boolean = true> {
  vereinsname?: T;
  logo?: T;
  claim?: T;
  adresse?: T;
  email?: T;
  telefon?: T;
  eishalle?: T;
  sozialeMedien?:
    | T
    | {
        plattform?: T;
        url?: T;
        id?: T;
      };
  sponsoringText?: T;
  sponsoringBlatt?: T;
  sponsoringKontakt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}